# Generated by Django 4.0.4 on 2022-05-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('memoire', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('prix', models.IntegerField()),
                ('resume', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
